server:
  port: 3000
spring:
  datasource:
    username: admin
    password: panrenhao
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.133.196.106:3306/giant-kitchen?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-Idle: 5
      max-Active: 20
      max-Wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: panrenhao
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
        config:
          enabled: true
logging:
  config: classpath:log4j2-spring.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl